FROM node:18 AS dev

WORKDIR /app
EXPOSE 4200

COPY package*.json ./

COPY . .
RUN npm install -g @angular/cli
RUN npm install

CMD ["ng", "serve", "--host", "0.0.0.0", "--configuration", "dev", "--poll", "1"]