FROM node:18 AS prod

WORKDIR /app

COPY package*.json ./

RUN npm install -g @angular/cli
RUN npm install

COPY . .

RUN npm run build

RUN ng build --configuration=production

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "1"]

