FROM node:18 AS prod

WORKDIR /app

COPY package*.json ./

RUN npm install -g @angular/cli
RUN npm install

COPY . .

RUN ng build --configuration=preprod

EXPOSE 4200

CMD ["ng", "serve", "--host", "--configuration=preprod", "0.0.0.0", "--poll", "1"]
