services:
  backend:
    container_name: sdm-frontend-container
    image: front-img
    restart: always
    ports:
      - "4200:4200"
    networks:
      - frontend-network
    labels:
      traefik.enable: "true"
      traefik.http.services.sdm-backend.loadbalancer.server.port: "8080"
      traefik.http.services.sdm-backend.loadbalancer.server.scheme: "http"
      traefik.http.routers.sdm-backend-https.entrypoints: "websecure"
      traefik.http.routers.sdm-backend-https.rule: "Host(`preprod.savvystudymate.com`)"
      traefik.http.routers.sdm-backend-https.tls: "true"
      traefik.http.routers.sdm-backend-https.tls.certresolver: "cloudflare"

networks:
  backend-network:
    external: true
  frontend-network:
    external: true
