FROM node:18 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build-gcp-prod

FROM nginx:latest

COPY --from=build /app/dist/studymate-frontend/browser/ /usr/share/nginx/html/

COPY nginx.prod.gcp.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Replace $PORT in Nginx config with Cloud Run PORT env var and start Nginx
CMD envsubst '$PORT' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'

