services:
    frontend-nginx:
        container_name: sdm-frontend-nginx-container
        image: front-img
        restart: always
        networks:
            - frontend-network
        volumes:
            - ./nginx.preprod.conf:/etc/nginx/conf.d/default.conf
        labels:
            traefik.enable: 'true'
            traefik.http.services.sdm-frontend.loadbalancer.server.port: '80'
            traefik.http.services.sdm-frontend.loadbalancer.server.scheme: 'http'
            traefik.http.routers.sdm-frontend-https.entrypoints: 'websecure'
            traefik.http.routers.sdm-frontend-https.rule: 'Host(`preprod.savvystudymate.com`) || Host(`test.savvystudymate.com`)'
            traefik.http.routers.sdm-frontend-https.tls: 'true'
            traefik.http.routers.sdm-frontend-https.tls.certresolver: 'cloudflare'

networks:
    backend-network:
        external: true
    frontend-network:
        external: true
