services:
    frontend:
        container_name: sdm-frontend-prod-container
        image: frontend-prod-img
        restart: always
        networks:
            - prod-network
        volumes:
            - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
        labels:
            traefik.enable: 'true'
            traefik.http.services.sdm-frontend.loadbalancer.server.port: '80'
            traefik.http.services.sdm-frontend.loadbalancer.server.scheme: 'http'
            traefik.http.routers.sdm-frontend-https.entrypoints: 'websecure'
            traefik.http.routers.sdm-frontend-https.rule: 'Host(`prod.savvystudymate.com`) || Host(`kmitl.savvystudymate.com`)'
            traefik.http.routers.sdm-frontend-https.tls: 'true'
            traefik.http.routers.sdm-frontend-https.tls.certresolver: 'cloudflare'

networks:
    prod-network:
        external: true
