FROM node:18 AS prod

WORKDIR /app
EXPOSE 4200

COPY package*.json ./

COPY . .
RUN npm install -g @angular/cli
RUN npm install

RUN ng build --configuration=prod

CMD ["ng", "serve", "--host", "0.0.0.0", "--configuration", "prod", "--poll", "1"]

