services:
    frontend:
        container_name: StudyMate-main-Nginx
        image: frontend-prod-img
        restart: always
        networks:
            - prod-network
        volumes:
            - ./nginx.prod.ce-cloud.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

networks:
    prod-network:
        external: true
