name: CI for StudyMate-Frontend Production Deployment

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'The branch to trigger the workflow on'
                required: true
                default: 'main'
                type: string

jobs:
    pull_image:
        name: Pull Frontend Image
        runs-on:
            labels: ['self-hosted', 'Linux', 'X64', 'prod-runner']

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Remove Old Docker Image
              run: |
                  docker image prune -f
                  docker rmi -f $(docker images -q frontend-prod-img) || true

            - name: Build Docker Image
              run: |
                  docker build -f Dockerfile.prod -t frontend-prod-img .

    deploy:
        name: Deploy Frontend to Production
        needs: pull_image
        runs-on:
            labels: ['self-hosted', 'Linux', 'X64', 'prod-runner']

        steps:
            - name: Stop and Remove Current Container
              run: |
                  docker compose -f docker-compose.prod.yml down -v || true

            - name: Deploy New Container
              run: |
                  docker compose -f docker-compose.prod.yml up -d --build

            - name: ✅✅ Finish ✅✅
              run: echo "Production deployment successful!"
