# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: StudyMate-Frontend

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Deploy-Frontend:
    runs-on:
     labels: [ 'self-hosted', 'Linux', 'X64' , 'front-runner' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.prod -t front-img .

      - name: Run Docker Container
        run: |
          docker run -d -p 4200:4200 --name sdm-frontend-container front-img

      - name: ✅✅ Finish ✅✅
        run: echo "All Passed => Fisnish !!"

      - name: Stop and Remove Container
        run: |
          docker stop sdm-frontend-container
          docker rm sdm-frontend-container

